### ISSUE TITLE
oauth2: introspection and revocation

### ISSUE THREAD

**Issue by jrossiter** [ory-am/fosite#111]
Do you think it's worth implementing interfaces for token introspection and revocation?

OAuth 2.0 Token Introspection: https://tools.ietf.org/html/rfc7662
OAuth 2.0 Token Revocation: https://tools.ietf.org/html/rfc7009

Seems like it would be possible to add to the OAuth2Provider interface and add some more interfaces:

- IntrospectRequester
- IntrospectResponder
- RevokeRequester
- RevokeResponder

Additional functions for the OAuth2Provider interface:

- NewIntrospectRequest
- NewIntrospectResponse
- WriteIntrospectError
- WriteIntrospectResponse
- NewRevokeRequest
- NewRevokeResponse
- WriteRevokeError
- WriteRevokeResponse

Would adding to OAuth2Provider break BC?

**Comment by arekkas** [comment]
I generally like the idea, we already have the [TokenValidator](https://github.com/ory-am/fosite/blob/master/validator.go#L11) interface which is helping [ValidateToken](https://github.com/ory-am/fosite/blob/master/oauth2.go#L116) and is sort of doing RFC7662, but you have to implement most of the things yourself.

Adding these things to the OAuth2Provider would break BC, but only if someone implements their own OAuth2 implementation which I doubt. Additionally, we're still in the `0.x.y` tag and labeled as release preview, so it should be ok!

**Comment by arekkas** [comment]
The question is if we even need both the request and the response object or if a simple `RevokeToken` is enough. For example, RFC7009 does not have a real response, just HTTP 200 OK: https://tools.ietf.org/html/rfc7009#section-2.2

**Comment by jrossiter** [comment]
That makes sense for revocation. 

What about a signature like this?

`func (f *Fosite) RevokeToken(rw http.ResponseWriter, req *http.Request)`

With this the function would be able to:

- verify the client (`req.BasicAuth`)
- verify token was issued to the client
- call revocation endpoint handlers to perform the clean up

This would require:

- RevocationEndpointHandler interface
- Addition to the Fosite struct

Am I on the right track with this? If so I can give it a shot.

**Comment by arekkas** [comment]
Yes, I think that's very close! I checked out the RFC and it includes the usual error handling from OAuth2, for example when the client credentials are invalid.

I think we should keep the practice of adding the context and maybe leave the response up to the caller:

```
RevokeToken(ctx context.Context, r *http.Request) error
```

and also include, as you initially suggested `WriteRevokationResponse`. Usage could look like this then:

```
func MyRevokeHandler(rw http.ResponseWriter, req *http.Request) {
  err := fosite.RevokeToken(context.Background(), req)
  fosite.WriteRevokationResponse(context.Background, rw, err)
}
```

What do you think?

**Comment by arekkas** [comment]
And `WriteRevokationResponse` returns either the usual error handling (similar to `WriteAccessError`) and 200 if no error was given.

**Comment by jrossiter** [comment]
Looks good!

**Comment by arekkas** [comment]
Awesome! So while you're working on token revocation, I'll start migrating some logic from the [Hydra introspection endpoint](https://github.com/ory-am/hydra/blob/master/oauth2/introspector.go) to fosite :)

**Comment by jrossiter** [comment]
There's a note in section 2.1: https://tools.ietf.org/html/rfc7009#section-2.1

> If the particular
   token is a refresh token and the authorization server supports the
   revocation of access tokens, then the authorization server SHOULD
   also invalidate all access tokens based on the same authorization
   grant (see Implementation Note).

Is there a way to determine which tokens were created by a specific refresh token?

**Comment by arekkas** [comment]
> Is there a way to determine which tokens were created by a specific refresh token? 

No, unfortunately not. It would be good to support that though, I have to think about this.

**Comment by jrossiter** [comment]
I'll close this as 0.4.0 now implements these.
