### ISSUE TITLE
oauth2: introspection handler excess calls

### ISSUE THREAD

**Issue by jrossiter** [ory-am/fosite#117]
I'm running a test server with all OAuth2 factories enabled.

In `func (f *Fosite) IntrospectToken`: `len(f.TokenIntrospectionHandlers)` returns 5 for the length.

Whenever a request for introspection comes in the same `IntrospectToken()` is run 5 times.
All validators return the same successful response.

Should these handler range loops return early when a non-error has been returned? 
Is this a side effect of having the `IntrospectToken` function on the `Fosite` OAuth2Provider? (and therefore all factories implement introspection)

**Comment by arekkas** [comment]
Ah yes, that's an issue with the composer I think. Usually it shouldn't add duplicates but I think due to the composed types it isn't detecting them as dupes. Thanks for the report
