### ISSUE TITLE
Remove the word "bad-ass" from project description.

### ISSUE THREAD

**Issue by abiosoft** [ory-am/fosite#12]
Gophers slack (http://gophers.slack.com) has the word in the bad words list. 

Considering that the slack community is one of the strongest Go community and it includes possible adopters of this library, I will advise removal or replacement with a more friendly word for the general audience.

Thanks.

**Comment by arekkas** [comment]
done ;)

**Comment by abiosoft** [comment]
So fast! :+1:

**Comment by arekkas** [comment]
Where you're right, you're right :)

**Comment by arekkas** [comment]
By the way, is http://gophers.slack.com/ an open channel or closed?

**Comment by abiosoft** [comment]
It is open, but requires invitation. http://bit.ly/gophers-slack-invite.

**Comment by arekkas** [comment]
Thanks :+1:
