### ISSUE TITLE
Session expiration using JWT with 0.5.0 ExpiresAt map

### ISSUE THREAD

**Issue by cristiangraz** [ory-am/fosite#120]
I'm using `OAuth2JWTStrategy` for tokens. I can't seem to get the tokens to have different expirations using the new `0.5.0` release. If I configure my session like this:

```go
type Session struct {
   // ...
   
   *oauth2.JWTSession
}
```

And initialize like this:
```
return &Session{
    JWTSession: &oauth2.JWTSession{
        JWTClaims: &jwt.JWTClaims{
            Issuer:    issuer,
            IssuedAt:  now,
            NotBefore: now,
            ExpiresAt: time.Now().Add(time.Hour * 6),
            Extra:     make(map[string]interface{}),
        },
        ExpiresAt: map[fosite.TokenType]time.Time{
            fosite.AuthorizeCode: now.Add(10 * time.Minute),
            fosite.AccessToken:   now.Add(1 * time.Hour),
            fosite.RefreshToken:  now.Add(2 * time.Hour),
        },
    },
}
```
I expect my JWT tokens for authorize code, access token, and refresh token to have the expirations listed above. All three always are set to the `JWTClaims.ExpiresAt` time (6 hours). If I omit the `JWTClaims.ExpiresAt` field hoping for it to be set based on the `JWTSession.ExpiresAt` map, a panic is thrown.

I'm able to get the authorize code to have a different expiration by doing this just before the `NewAuthorizeResponse` is created:

`session.JWTClaims.ExpiresAt = session.GetExpiresAt(fosite.AuthorizeCode)`

Am I misunderstanding how the new `ExpiresAt` map should work, or is it perhaps an issue with the JWT strategy?

**Comment by arekkas** [comment]
Ha, that looks like an issue with the JWT strategy. The code is correct. The issue is that currently, the data from JWT is used to perform the expiration and the data from the session is disregarded. This is obviously confusing, because the new session interface has those parameters.

**Comment by arekkas** [comment]
It would probably make sense to remove the ExpiresAt value from the JWT claims (or make it private) and set it via the session data instead of manually.

**Comment by cristiangraz** [comment]
@arekkas agreed, I have it in there for the example (and to prevent panics). I agree that it makes sense to remove and pull it from the `ExpiresAt` map.

Maybe the `oauth2.RS256JWTStrategy` can pass in the `TokenType` when calling `jwt. RS256JWTStrategy.Generate` as the first parameter, and the `ExpiresAt` claim can be set based on the session's `ExpiresAt` map? Let me know if that approach sounds reasonable to you and I can work on a PR.

**Comment by arekkas** [comment]
> Maybe the oauth2.RS256JWTStrategy can pass in the TokenType when calling jwt. RS256JWTStrategy.Generate as the first parameter

You don't actually need to do that, because the token type is already implied by the API, for example: https://github.com/ory-am/fosite/blob/master/handler/oauth2/strategy_jwt.go#L27

> and the ExpiresAt claim can be set based on the session's ExpiresAt map

Yes, that sounds very reasonable! I would appreciate a PR a lot :)

**Comment by cristiangraz** [comment]
@arekkas Ahh right, much simpler. I'll send over a PR shortly.

**Comment by arekkas** [comment]
Awesome :)
