### ISSUE TITLE
JWT Support

### ISSUE THREAD

**Issue by leetal** [ory-am/fosite#16]
@arekkas Since i'm a big fan of Hydra and also know that Hydra uses JWT, it would probably be good to add support in Fosite for JWT as well. Since JWT is gaining a lot of focus these days you know ;)

I really like the stateless behaviour of JWT and the ability to put arbitary data into it and lastly that you can validate it without a call to the database. That makes it more robust and easy to use in a multi-service environment, where multiple services need to validate the authenticity of a resource owner.

I know that with enigma, there should really be no hussle to do it quickly. Especially since you basically just can drag and drop the JWT folder of Hydra into Fosite and then modify enigma a little to support pluggable token generators. 

What do you think? If you need help implementing anything, just shout out. I can help you! :+1:

**Comment by arekkas** [comment]
I'm curious if developers understand my code :) The enigma interface is pretty much finalized so if you'd like give it a shot!

I think JWT support is a good idea! :) We might have to adapt the enigma API a little bit to get the request data into enigma, but just give it a shot and if you encounter problems ping me :)

**Comment by leetal** [comment]
I'll work on it after work the coming 2 days then! Expect it to be "working" by Wednesday!

**Comment by arekkas** [comment]
Nice, looking forward :+1:

**Comment by arekkas** [comment]
By the way, if you want to chat real time we could think of setting up a fosite or ory chat on https://gitter.im/

**Comment by leetal** [comment]
A quick update: JWT is now working in conformance to enigma interface. All unit tests pass. Will add this to the example tomorrow (a little sparse on spare time atm.) so a developer easily can switch between standard hmac256 or JWT (using RSA256, certificates). After that I'll create a PR so we can discuss further :)

**Comment by arekkas** [comment]
nice! looking forward :)

**Comment by arekkas** [comment]
Closed as per #11
