### ISSUE TITLE
Do you consider this production ready?

### ISSUE THREAD

**Issue by kmulvey** [ory-am/fosite#30]
The only hint I've seen is this:

"Once releases roll out, you will be able to fetch a specific fosite API version through gopkg.in. As of now, no stable v1 version exists."

**Comment by arekkas** [comment]
In terms of API: Public facing API (not to confuse with internal public API) is pretty stable. If you need 100% api stability I'd wait for v1.

In terms of battle-tested: Fosite has not been tested in a production system by myself yet.

**Comment by arekkas** [comment]
A little more insight into stability: #31 is a rework of the APIs and will be an almost freezed API. Once I implement fosite in hydra I will freeze the fosite API.
