### ISSUE TITLE
Installation fails on go 1.5.3

### ISSUE THREAD

**Issue by sharpner** [ory-am/fosite#33]
I tried following the readme and install the v0 branch with the following command:
```go get gopkg.in/ory-am/fosite.v0/...```

This results in the following error:
```package gopkg.in/ory-am/fosite.v0/fosite-example imports github.com/ory-am/fosite/fosite-example/internal: use of internal package not allowed```

This works:
```go get gopkg.in/ory-am/fosite.v0/```

Is this just a documentation problem?

Thanks for the help

**Comment by arekkas** [comment]
Yes this is a doc error :)

**Comment by sharpner** [comment]
k thx ;)

**Comment by plandem** [comment]
still persists

**Comment by arekkas** [comment]
@plandem are you sure this is the same issue and not #57 ?

**Comment by plandem** [comment]
i'm getting both!

**Comment by plandem** [comment]
```
imports github.com/ory-am/fosite/internal: use of internal package not allowed
```

if i comment this, then i'm getting:
```
../../go/src/github.com/ory-am/fosite/token/jwt/jwt.go:29: cannot use claims.ToMap() (type map[string]interface {}) as type jwt.Claims in assignment:
        map[string]interface {} does not implement jwt.Claims (missing Valid method)
```

**Comment by arekkas** [comment]
please use go get -u github.com/ory-am/fosite` to install this package
