### ISSUE TITLE
Questions about sessions

### ISSUE THREAD

**Issue by saintfiends** [ory-am/fosite#35]
In https://github.com/ory-am/fosite#exemplary-authorization-endpoint it says:
 
    // Now it's time to persist some data. This session will be later available to us in the token endpoint.
    // So make sure to store things like the user id here.
    // The authorize request will be stored additionally, so no need to save scopes or similar things.
    sess := &session{User: "peter"}

and in https://github.com/ory-am/fosite#exemplary-token-endpoint:

    // Remember the sesion data from before? Yup, that's going to be saved in here!
    var mySessionData session

    // This will create an access request object and iterate through the registered TokenEndpointHandlers to validate the request.
    accessRequest, err := oauth2.NewAccessRequest(ctx, req, &mySessionData)
    if err != nil {
        log.Printf("Error occurred in NewAccessRequest: %s\nStack: \n%s", err, err.(*errors.Error).ErrorStack())
        oauth2.WriteAccessError(rw, accessRequest, err)
        return
    }

    // Now we have access to mySessionData's populated values and can do crazy things.

I want to understand how one would use this session, who is supposed to fill the session with data, the storage?

**Comment by arekkas** [comment]
The session is three things:

1. A way to persist data across `/auth` and `/token` endpoints. For example: The token endpoint *probably* wants to know *who* gave consent - that data is however only available at the `/auth` endpoint. Therefore we need to persist some sort of state across requests.
2. Some fosite extensions (for example ID Tokens or JWT Access Tokens) also need to know some data (e.g. which user, what time, which scope, ...). This is also what the session is for.
3. Anything you want to be available at the `/token` endpoint. Let's say the users phone number to notify him when someone requested an access token!

What the session looks like is depending on what functionality you use (JWT for example demands a specific session type) and what data you want to have. If you ever worked with [osin](https://github.com/RangelReale/osin), the session is basically the `UserData` object.

Also check out the [example](https://github.com/ory-am/fosite/blob/master/fosite-example/main.go). It explain things even more.

**Comment by saintfiends** [comment]
So Storage implementation is supposed to serialize and store session information, right?

**Comment by arekkas** [comment]
Yup

**Comment by saintfiends** [comment]
Thanks for the prompt response. I think that description is a perfect fit for the documentation.
