### ISSUE TITLE
Improve error wrapping

### ISSUE THREAD

**Issue by arekkas** [ory-am/fosite#46]

**Comment by otraore** [comment]
I would like to recommend you put a comment stating what closed the issue, whether it's a commit PR etc. As always, thank you for the project, looking forward to using it.

**Comment by arekkas** [comment]
You where a little bit faster then me ;) superseded by #50

**Comment by otraore** [comment]
I'm not sure if we're talking about the same thing?

**Comment by arekkas** [comment]
No, you're absolutely right. Closing issues should always come with a comment. What I tried to say was I redefined the issue and created a new one for it, but something disrupted me and I forgot to do it.

**Comment by arekkas** [comment]
superseded by #50

**Comment by otraore** [comment]
Oh right glad we're on the same page. Thank you again.
