### ISSUE TITLE
Return context

### ISSUE THREAD

**Issue by ADone** [ory-am/fosite#56]
Hi! I have special case for returning some additional signatures from such methods like `CreateAccessTokenSession`.
And I have just added a return context for ALL endpoints & storages. For example:
```go
type AuthorizeCodeStorage interface {
	CreateAuthorizeCodeSession(
		ctx context.Context,
		code string,
		request fosite.Requester,
	) (context.Context, error)

	GetAuthorizeCodeSession(
		ctx context.Context,
		code string,
		session interface{},
	) (context.Context, fosite.Requester, error)

	DeleteAuthorizeCodeSession(
		ctx context.Context,
		code string,
	) (context.Context, error)
}
```
All tests passes!
Do you interest in that functionality?

**Comment by arekkas** [comment]
sure, create a PR and I will take a look :)

**Comment by ADone** [comment]
@arekkas could you close this too?)
