### ISSUE TITLE
oauth2: how to revoke tokens?

### ISSUE THREAD

**Issue by 256dpi** [ory-am/fosite#73]
Are there any plans on implementing token revocation as per https://tools.ietf.org/html/rfc7009?

It seems to me that the library is prepared to have this functionality at some point as there is the yet unused `DeleteAccessTokenSession` method on the `Storage` interface.

**Comment by arekkas** [comment]
Currently, there is no standard way but it's a good idea to have this similar to token validation. However, you're right, by using the DeleteAccessTokenSession you can already achieve that

**Comment by arekkas** [comment]
see #112
