### ISSUE TITLE
How to run fosite example in my own folder

### ISSUE THREAD

**Issue by aantelov87** [ory-am/fosite#74]
For now I just move the fosite example to my own package folder and I am getting the error  about the types:

 cannot use clientConf (type "golang.org/x/oauth2".Config) as type "github.com/ory-am/fosite/vendor/golang.org/x/oauth2".Config in argument to pkg.HomeHandler

I understand that the error is caused because inside of fosite you are using glide as a dependencies management and it tries to match two differents types but 

what is the best path to follow in this case?

Thx

**Comment by arekkas** [comment]
what version of go are you using? it is recommended to use go 1.6 or 1.7

**Comment by arekkas** [comment]
Closing because missing response
