### ISSUE TITLE
Consider upgrading to jwt-go 3.0.0

### ISSUE THREAD

**Issue by leetal** [ory-am/fosite#76]
Hi Aeneas!

So, i'm still following the development of all your libraries and we've just now started to implement our interfaces against fosite/hydra. It came to a quick halt when we realized that fosite relies upon v2.7.0 of jwt-go, and that we must use 3.0.0 of jwt-go. We also use glide and this is causing a clash since jwt-go have introduced a breaking change by replacing the map[string]interface{} to a jwt.Claims interface (essentially exactly like your jwt_claims.go). 

Do you want help fixing this change (more or less just upgrade to 3.0.0 of jwt-go and create a new type that implements the Claims interface in fosite) or is this on your backlog?

Regards
Alexander W

**Comment by arekkas** [comment]
@leetal yes, I welcome if you could help me with upgrading to 3.0. This has been a pain ever since they broke bc. :)
