### ISSUE TITLE
docs: fosite-example shouldn't rely on camlistore dependency

### ISSUE THREAD

**Issue by arekkas** [ory-am/fosite#89]

**Comment by otraore** [comment]
Camlistore?

**Comment by arekkas** [comment]
yes, it seems like the google oauth2 package is depending on googlestore which depends on camlistore, so fosite-example implicitly fetches those...

**Comment by arekkas** [comment]
hm @danilobuerger I can't reproduce your output from yesterday. I can see the `appengine` dependency in [glide.lock](https://github.com/ory-am/fosite/blob/master/glide.lock) but I can't see anything with camlistore in neither the lock file (which contains all circular dependencies) nor in my vendor directory. Maybe gb did more than it should, closing.

**Comment by danilobuerger** [comment]
Its with gvt not gb. The output is:

```
· Fetching recursive dependency: golang.org/x/oauth2
·· Fetching recursive dependency: cloud.google.com/go/compute/metadata
··· Fetching recursive dependency: cloud.google.com/go/internal
···· Fetching recursive dependency: google.golang.org/grpc
····· Fetching recursive dependency: golang.org/x/net/http2
······ Fetching recursive dependency: go4.org/syncutil/singleflight
······ Fetching recursive dependency: camlistore.org/pkg/googlestorage
```

**Comment by danilobuerger** [comment]
Maybe @FiloSottile knows why?

**Comment by arekkas** [comment]
Ah sorry, I mixed that up. Go has too many vendor managers :D

**Comment by arekkas** [comment]
Maybe it has to do something with the internal package.

**Comment by arekkas** [comment]
Also, on a side note, installing fosite with `glide install` is ok fast, even on usually slow travis root builds!
